updates for pth checks

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -54,12 +54,16 @@ if [ -n "$PTH_CFLAGS" ]; then
     LIBS="$LIBS $PTH_LIBS";
     printf "         Done.\n";
 else
-    opwd=`pwd`
-    cd jabberd/pth-1.3.7;
-    ./configure || (printf "Error Configuring pth"; exit 1);
-    cd $opwd;
-    PSUBDIR="pth-1.3.7"
-    PLINK=`pwd`"/jabberd/pth-1.3.7/.libs/libpth.a"
+    if [ -d "jabberd/pth-1.3.7" ]; then
+        opwd=`pwd`
+        cd jabberd/pth-1.3.7;
+        ./configure || (printf "Error Configuring pth"; exit 1);
+        cd $opwd;
+        PSUBDIR="pth-1.3.7";
+        PLINK=`pwd`"/jabberd/pth-1.3.7/.libs/libpth.a";
+    else
+        printf "          Error.\n\n No version of PTH is available on this system\nhttp://www.gnu.org/software/pth/";
+    fi
 fi
 
 ##
