pth support

diff --git a/jabberd14/configure b/jabberd14/configure
--- a/jabberd14/configure
+++ b/jabberd14/configure
@@ -22,10 +22,17 @@ PTH_CFLAGS=`pth-config --cflags`
 PTH_LDFLAGS=`pth-config --ldflags`
 PTH_LIBS=`pth-config --libs`
 if [ -n "$PTH_CFLAGS" ]; then
+    CFLAGS="$CFLAGS $PTH_CFLAGS";
+    LDFLAGS="$LDFLAGS $PTH_LDFLAGS";
+    LIBS="$LIBS $PTH_LIBS";
     printf "         Done.\n";
 else
-    printf "You are missing pth-config.  This is obtained from the pth package that can be found at http://www.gnu.org.  Please install this package and then run configure again.\n";
-    exit 1;
+    opwd=`pwd`
+    cd jabberd/pth-1.3.7;
+    ./configure || (printf "Error Configuring pth"; exit 1);
+    cd $opwd;
+    PSUBDIR="pth-1.3.7"
+    PLINK=`pwd`"/jabberd/pth-1.3.7/.libs/libpth.a"
 fi
 
 ##
@@ -36,10 +43,10 @@ if [ -n "$CC" ]; then
 else
     CC="gcc";
 fi;
-CFLAGS="$CFLAGS -g -Wall -fPIC -I./ -I../ $PTH_CFLAGS"
+CFLAGS="$CFLAGS -g -Wall -fPIC -I./ -I../"
 MCFLAGS="$MCFLAGS -shared"
-LDFLAGS="$LDFLAGS $PTH_LDFLAGS"
-LIBS="$LIBS $PTH_LIBS"
+LDFLAGS="$LDFLAGS"
+LIBS="$LIBS"
 XLDFLAGS="$XLDFLAGS "
 JHOME=`pwd`
 
@@ -68,6 +75,7 @@ printf "     Done.\n"
 # Output our settings for usage
 ##
 printf "Generating Settings Script..."
+echo 1 > test.out
 cat << EOF > platform-settings
 #!/bin/sh
 CC=$CC
@@ -76,6 +84,8 @@ MCFLAGS=$MCFLAGS
 LDFLAGS=$LDFLAGS
 LIBS=$LIBS
 XLDFLAGS=$XLDFLAGS
+PSUBDIR=$PSUBDIR
+PLINK=$PLINK
 JHOME=$JHOME
 EOF
 chmod 0700 platform-settings
